Set up services
gravitational/blog pull request #11
Opened 2022-02-04 09:23 UTC by Alqanar

- fixed favicon;
- removed styles with '::before' 
Unfortunately due to the fact that the next loader does not always work well with styled-components I had to remove styling rss links in Blog and BlogArticle components, including the change in color of rss icons when hovering over the link.

2022-02-09 12:28 UTC, iAdramelk requested changes

2022-02-09 12:28 UTC, iAdramelk commented on components/ArticleCard/ArticleCard.tsx
> +  let extension = "";
Q: WDYT about moving url manipulations and `needImg` check inside the `getStaticProps`? You have all the data you need to create url there and you can just return complete url in `meta.frontmatter.logo.image` and insert it if it is needed. This will make front-end component simpler and smaller. Also it is a good idea to reuse the naming function from the back to generate names so you don't need to update name format in two separate places.

2022-02-09 12:28 UTC, iAdramelk commented on components/MarketoForm/helpers.ts
> +const SUBSCRIPTION_FOR_ID = process.env.NEXT_PUBLIC_EMAIL_SUBSCRIPTION_FORM_ID;
```suggestion
const SUBSCRIPTION_FORM_ID = process.env.NEXT_PUBLIC_EMAIL_SUBSCRIPTION_FORM_ID;
```

2022-02-09 12:28 UTC, iAdramelk commented on components/MarketoForm/helpers.ts
> +    const response = await fetch(`/blog/api/form/${SUBSCRIPTION_FOR_ID}/`, {
```suggestion
    const response = await fetch(`/blog/api/form/${SUBSCRIPTION_FORM_ID}/`, {
```

2022-02-09 12:28 UTC, iAdramelk commented on components/MarketoForm/helpers.ts
> +  const id = SUBSCRIPTION_FOR_ID;
```suggestion
  const id = SUBSCRIPTION_FORM_ID;
```

2022-02-09 12:28 UTC, iAdramelk commented on scripts/extract-article-covers.mjs
> +  const sourceName = resolve(`./pages/${cover.uri}/${cover.image}`);
Let's move logic to generate new location to the separate function and reuse it for generating names for the frontend. Right now it will be easy to break covers if you change folder or name pattern in one place and forgot to do it in another.

2022-02-09 12:28 UTC, iAdramelk commented on scripts/extract-article-covers.mjs
> +import { resolve } from "path";
Let's add comments for each server file that describes why it is exists.

2022-02-09 12:28 UTC, iAdramelk commented on package.json
> +    "dev": "yarn build-node && yarn extract-article-covers && next dev",
If you add new post without restarting the server, images will not be updated. We probably need to add comment about in either in readme or in the code itself.

Also let's add `extract-article-covers` to readme.

2022-02-09 12:28 UTC, iAdramelk commented on server/found-article-images.ts
> +import { BlogMeta } from "layouts/BlogArticle/types";
Q: Maybe `find-article-images.ts` will be more correct in this case?

2022-02-09 12:28 UTC, iAdramelk commented on server/found-article-images.ts
> +// These images are needed on the main page of the blog.
We should add info that we need these images not only for the main page, but for each tag's page too.

2022-02-09 12:28 UTC, iAdramelk commented on server/pages-helpers.ts
> +          new Date(a.frontmatter.date).getTime()
I think that you can use built-in methods if `getPagesInfo` for filtering and sorting here if I don't miss anything, it also have built-in sorting for dates. See https://github.com/gravitational/blog/blob/2fed712ac3d0cb1c1894f4bcaab191d8ef1f21b7/server/pages-helpers.ts#L64-L67

It would look something like:

```
 getPagesInfo<BlogMeta>(`**/*.mdx`, {
  sort: "date",
  order: "DESC",
  filter: ({ layout }) => layout === "blogArticle",
})
  .map(({ data }) => data)
```

2022-02-09 12:49 UTC, Alqanar commented on package.json
> +    "dev": "yarn build-node && yarn extract-article-covers && next dev",
yep, thx

2022-02-09 12:50 UTC, Alqanar commented on server/found-article-images.ts
> +import { BlogMeta } from "layouts/BlogArticle/types";
yep, thx

2022-02-09 13:05 UTC, Alqanar commented on server/pages-helpers.ts
> +          new Date(a.frontmatter.date).getTime()
Yep, I used these features in the script. I rewrote it here, thx.

2022-02-09 13:43 UTC, Alqanar commented on package.json
> +    "dev": "yarn build-node && yarn extract-article-covers && next dev",
Yes, thank you. But I wanted to add quite a bit to the README a little later. Adding a description of this script was among the plans.

2022-02-10 07:31 UTC, iAdramelk commented on components/ArticleCard/ArticleCard.tsx
> +import { resolve } from "path";
Do we need path here?

2022-02-10 07:31 UTC, iAdramelk commented on tsconfig.node.json
> +    "utils/generate-cover-image-path.ts"
Did the build break without it? Theoretically all includes should be resolved automatically even if it is not in this folder.

2022-02-10 07:31 UTC, iAdramelk commented on utils/generate-cover-image-path.ts
> +import { resolve } from "path";
Will `path` work in browser and how much bundle size it will add?

2022-02-10 08:11 UTC, Alqanar commented on tsconfig.node.json
> +    "utils/generate-cover-image-path.ts"
Yep, without a forced reference the function was not copied

2022-02-10 08:27 UTC, Alqanar commented on utils/generate-cover-image-path.ts
> +import { resolve } from "path";
Yes, it work. 4.29KB

2022-02-10 08:31 UTC, iAdramelk commented on utils/generate-cover-image-path.ts
> +import { resolve } from "path";
Lets leave it for now, but we should move it to `getStaticProps` at some point, 4Kb+ for merging 2 strings is a lot.

2022-02-10 09:03 UTC, iAdramelk approved these changes

2022-02-10 09:27 UTC, merged