added sitemap to the blog
gravitational/blog pull request #27
Opened 2022-02-14 08:11 UTC by Alqanar

2022-02-14 09:52 UTC, iAdramelk requested changes

2022-02-14 09:52 UTC, iAdramelk commented on .gitignore
> +/public/blog_sitemap.xml
We can just call it `sitemap.xml`  here. It will be easy to distinguish them by urls, e. g. `/blog/sitemap.xml`, `/docs/sitemap.xml`..

2022-02-14 09:52 UTC, iAdramelk commented on next.config.mjs
> +import { generateSitemap } from "./.build/server/sitemap.mjs";
Let's move it to `/scripts/`, like `yarn generate-rss`. It will be easier to test and document (it was mistake for me to add in the next config in the first place).

2022-02-14 09:52 UTC, iAdramelk commented on server/sitemap.ts
> +  const blogPages = getBlogPaths().map((loc) => ({ loc }));
This way only posts will be added to sitemap. Index will not be there (we definitely want index here). Also we will not have tag pages (do we need them? Let's ask Alex).

2022-02-15 12:39 UTC, Alqanar commented on server/sitemap.ts
> +  const blogPages = getBlogPaths().map((loc) => ({ loc }));
Alex said that if not in the existing sitemap, then do not add links. The existing sitemap only has a link to the blog's index page and to the articles. I added the index page.

2022-02-15 12:55 UTC, iAdramelk approved these changes

2022-02-15 12:55 UTC, iAdramelk commented on scripts/generate-sitemap.mjs
> +    .sync(join(pagesRoot, `**/*.{${extensions.join()}}`))
Just a thought, we can do it in separate PR, but we can simplify page finding logic. We actuall does not need `extensions`, `ignorePages` or `filter` here. We can just find all pages with `mdx` extension, because in the blog we only use them. In the main site these things are used because we have some `tsx` and `jsx` pages, but not here.

2022-02-15 13:05 UTC, merged