Fix bug, add latest post
gravitational/blog pull request #47
Opened 2022-03-07 18:26 UTC by sandylcruz

2022-03-07 22:21 UTC, C-STYR requested changes

2022-03-07 22:21 UTC, C-STYR commented on layouts/BlogArticle/BlogArticle.tsx
> +    .filter((article) => Boolean(article.frontmatter.logo)) // filter out posts without cover photo
It looks like we're running `filter` twice; can this be refactored? At some point we are going to have a lot of blog articles and performance/SEO will take a hit...

2022-03-08 01:54 UTC, sandylcruz commented on layouts/BlogArticle/BlogArticle.tsx
> +    .filter((article) => Boolean(article.frontmatter.logo)) // filter out posts without cover photo
Addressed by using a single filter to check for both conditions. `articlesInfo` only returns the last 6 blog posts, not all of articles so not that big of a cost.

2022-03-09 00:17 UTC, C-STYR approved these changes

2022-03-09 00:18 UTC, merged